### ISSUE TITLE
Pre-Flight Checklist

### ISSUE THREAD

**Issue by juliusakula** [murdockfpv/murdockfpv.github.io#13]
### At-Home:

All batteries should be charged near 100%:

- [ ] Mavic Controller
- [ ] 3x Mavic Batteries
- [ ] iPad
- [ ] Cell phone
- [ ] Air-Pods
- [ ] AC Battery pack

Check Sandpoint METAR (Weather): [aviationweather.gov](https://www.aviationweather.gov/adds/tafs/?station_ids=KSZT&std_trans=translated&submit_both=Get+TAFs+and+METARs)

Double-check airspace on [SkyVector](https://skyvector.com/)

Check check SD card on drone

Inspect propellors for damage

#### Pack list:

- [ ] Mavic Air 2, batteries, fliters, cables
- [ ] iPad, Tablet Mount
- [ ] Air-Pods
- [ ] AC Battery pack
- [ ] Launch pad, Safety Cone/s
- [ ] Gloves, face mask for cold weather (Any flight below 40* F)
- [ ] Phone/Keys/Wallet(UAS License)

### Before take-off

* Check NOTAMS on B4UFLY app
* Calibrate Gimbal
* Clear take off area
* Enter airplane mode on cell phone, open Dictate app, press "start" with airpods connected.

Discuss with non-crewmembers

- [ ] "While I am flying, allow me to do my job and give me the space I need, I'll invite you to look at the screen occasionally, but for the most part you should not be hovering over my shoulder. Your photos are going to look great. I ask that you respect if I ask you to give me space."
